# prettier-ignore
version: '3.9'
services:
  server:
    build: 
      context: .
      args:
        - NODE_ENV=development
    container_name: development_web_server
    ports:
      - "5000:5000"
    depends_on:
      - postgres_database
      - cache    
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./env/.env
    command: npm run dev

  postgres_database:
    image: postgres:latest
    restart: always
    container_name: postgres_database
    env_file:
      - ./env/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - '4321:5432'
  
  redis_cache:
    image: redislabs/redismod
    container_name: redis_cache
    ports:
      - '6378:6379'
    volumes: 
      - ./redis-cache:/data
  # redis:
  #   image: redis
  #   restart: always
  #   container_name: redis
  #   ports:
  #     - '6378:6379'
  #   command: redis-server --save 20 1 --loglevel warning
  #   volumes: 
  #     - ./redis-data:/data
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   restart: always
  #   env_file:
  #     - ./env/.env
  #   ports:
  #     - "5050:80"

volumes:
  postgres_data:
  redis-data:
