# prettier-ignore
version: '3.9'
services:
  server:
    build: 
      context: .
      args:
        - NODE_ENV=development
    container_name: development_web_server
    ports:
      - "5000:5000"
    depends_on:
      - postgres_database
      - redis_cache    
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./env/.env
    command: npm run dev

  postgres_database:
    image: postgres:14.1
    restart: always
    container_name: postgres_database
    ports:
      - "2020:5432"
    env_file:
      - ./env/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis_cache:
    image: redislabs/redismod
    container_name: redis_cache
    ports:
      - '6378:6379'
    volumes: 
      - ./redis-cache:/data
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   restart: always
  #   env_file:
  #     - ./env/.env
  #   ports:
  #     - "5050:80"

volumes:
  postgres_data:
  redis-data:
