# prettier-ignore
version: '3.9'
services:
  server:
    build: 
      context: .
      args:
        - NODE_ENV=production
    env_file:
      - ./env/production.env
    command: ts-node src/server.ts
