# prettier-ignore
version: '3.9'
services:
  server:
    build: 
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./env/development.env
    command: npm run dev
